# Generated by Django 2.2.16 on 2023-04-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='profile',
        ),
    ]
