# Generated by Django 2.2.16 on 2023-04-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0002_auto_20230405_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='user',
        ),
    ]
