# Generated by Django 2.2.16 on 2023-04-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0005_auto_20230405_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
    ]
