# Generated by Django 2.2.16 on 2023-04-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0008_auto_20230405_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
