# Generated by Django 2.2.16 on 2023-04-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0009_auto_20230405_1832'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
