# Generated by Django 2.2.16 on 2023-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0010_auto_20230405_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
