# Generated by Django 2.2.16 on 2023-04-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0011_auto_20230414_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
