# Generated by Django 2.2.16 on 2023-04-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0013_auto_20230419_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
