# Generated by Django 2.2.16 on 2023-04-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0014_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=255)),
                ('user_phone_number', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('user_type', models.CharField(max_length=255)),
                ('organize_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('city_id', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('area_id', models.IntegerField()),
                ('gst_no', models.CharField(max_length=20)),
                ('id_proof', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Uer',
            },
        ),
    ]
