# Generated by Django 2.2.16 on 2023-04-19 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0015_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
