# Generated by Django 2.2.16 on 2023-04-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0016_auto_20230419_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Signup',
            },
        ),
    ]
