# Generated by Django 2.2.16 on 2023-04-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0017_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('u_name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
    ]
