# Generated by Django 2.2.16 on 2023-04-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0018_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('u_email', models.EmailField(max_length=255)),
                ('comment', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
