# Generated by Django 2.2.16 on 2023-04-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0019_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
