# Generated by Django 3.2.5 on 2023-04-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0023_rename_id_category_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='P_Category',
        ),
        migrations.RenameField(
            model_name='p_category',
            old_name='key',
            new_name='id',
        ),
        migrations.AlterModelTable(
            name='p_category',
            table='P_Category',
        ),
    ]
