# Generated by Django 3.2.5 on 2023-04-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0026_order_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
