# Generated by Django 3.2.5 on 2023-05-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0028_auto_20230501_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_phone_number',
            new_name='phone_number',
        ),
    ]
