# Generated by Django 3.2.5 on 2023-05-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0030_sign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
