# Generated by Django 3.2.5 on 2023-05-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0033_auto_20230501_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
