# Generated by Django 3.2.5 on 2023-05-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vadmin', '0034_delete_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Sign',
            },
        ),
    ]
